[program:trivebuzzmedia-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/trivebuzzmedia_blog/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/trivebuzzmedia_blog/storage/logs/worker.log
stopwaitsecs=3600

[program:trivebuzzmedia-scheduler]
process_name=%(program_name)s
command=php /var/www/trivebuzzmedia_blog/artisan schedule:run
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/trivebuzzmedia_blog/storage/logs/scheduler.log
